name: flutter_tianji
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: ^4.0.3
  shared_preferences: ^0.5.6+2
  dio: ^3.0.8
  fluttertoast: ^3.1.3
  bot_toast: ^3.0.0 # toast
  encrypt: ^4.0.2 #加密
  loading_indicator_view: ^1.1.0
  device_info: ^0.4.2+4 #设备信息
  flutter_screenutil: ^1.0.2 #屏幕分辨率
  path_provider: ^1.6.5
  common_utils: ^1.2.1 #常用工具类 时间轴 倒计时 正则 加密
  webview_flutter: ^0.3.22+1
  pull_to_refresh: 1.6.3
  cookie_jar: ^ 1.0.0
  date_format: ^1.0.8
  fluro: ^1.7.8
  flutter_swiper: ^1.1.6 #banner 轮播
  extended_image: ^0.7.3+1 #网络图片缓存
  event_bus: ^1.1.1 #消息总线
  qr_flutter: ^3.1.0 #二维码生成
  image_gallery_saver: ^1.2.2 #保存图片
  permission_handler: ^5.0.0+hotfix.5 #获取权限
  image_picker: ^0.6.6+1 # 相机拍照选取相册
  flutter_html: ^1.0.0
  barcode_scan: ^3.0.1
  url_launcher: ^5.4.7
  percent_indicator: ^2.1.3  
  flutter_app_upgrade: ^1.0.2 
  fsuper: ^0.1.5 
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  fl_chart: ^0.12.3 # 策略折线图
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splash/
    - images/tabBar/
    - images/home/
    - images/login/
    - images/wallet/
    - images/mine/
    - images/business/
    - images/baike/
    - images/strategy/

    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
